name: Deploy Skin Lendária

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 46.224.63.38
          username: root
          port: 2222
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/skinlendaria
            git pull origin main
